// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CLCommon.Models;

public partial class CorsoAcademyContext : DbContext
{
    public CorsoAcademyContext()
    {
    }

    public CorsoAcademyContext(DbContextOptions<CorsoAcademyContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TComune> TComunes { get; set; }

    public virtual DbSet<TProvincium> TProvincia { get; set; }

    public virtual DbSet<TRegione> TRegiones { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
       // => optionsBuilder.UseSqlServer("Data Source=PCLAB-112\\MSSQLSERVER01;Initial Catalog=CorsoAcademy;Integrated Security=False;User=CorsoAcademy;Password=CorsoAcademy01!;TrustServerCertificate=Yes;");
        => optionsBuilder.UseSqlServer("Data Source=FRANCESCO;Initial Catalog=CorsoAcademy;Integrated Security=False;User=CorsoAcademy;Password=CorsoAcademy01!;TrustServerCertificate=Yes;");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TComune>(entity =>
        {
            entity.HasOne(d => d.IdProvinciaNavigation).WithMany(p => p.TComunes).HasConstraintName("FK_T_Comune_T_Provincia");
        });

        modelBuilder.Entity<TProvincium>(entity =>
        {
            entity.HasOne(d => d.IdRegioneNavigation).WithMany(p => p.TProvincia).HasConstraintName("FK_T_Provincia_T_Regione");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}